[package]
name = "onboarding-rust"
version = "0.1.0"
authors = ["joylabs"]
edition = "2018"

[dependencies]
regex           = "1"
serde_json      = "1.0"
inflections = "1.1.1"
itertools = "0.8"

[dev-dependencies]
criterion = "0.2"

[profile.release]
debug = true
